services:
  api:
    image: node:22.21.1
    container_name: ncs-api-prod
    init: true
    restart: always
    networks:
      - nishikata-coast-story
      - reverse-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.ncs-api-prod.entrypoints=websecure
      - traefik.http.routers.ncs-api-prod.tls.certresolver=mydnsjp
      - traefik.http.routers.ncs-api-prod.rule=Host(`${NCS_API_HOST}`)
      - traefik.http.services.ncs-api-prod.loadbalancer.server.port=${NCS_API_PORT}
    environment:
      - NCS_ENV=${NCS_ENV}
      - TZ=Asia/Tokyo
    volumes:
      - ./app:/workspace/nishikata-coast-story/app
      - ./constant-variable:/workspace/nishikata-coast-story/constant-variable
      - ./prisma/model:/workspace/nishikata-coast-story/prisma/model
      - ./prisma/schema.prisma:/workspace/nishikata-coast-story/prisma/schema.prisma:ro
      - ./.env.keys:/workspace/nishikata-coast-story/.env.keys:ro
      - ./hono.prod.env:/workspace/nishikata-coast-story/hono.prod.env:ro
      - ./prisma.prod.env:/workspace/nishikata-coast-story/prisma.prod.env:ro
      - ./package.json:/workspace/nishikata-coast-story/package.json:ro
      - ./package-lock.json:/workspace/nishikata-coast-story/package-lock.json:ro
      - ./tsconfig.json:/workspace/nishikata-coast-story/tsconfig.json:ro
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
    working_dir: /workspace/nishikata-coast-story
    command:
      - bash
      - -c
      - |
        npm install -g @dotenvx/dotenvx
        npm clean-install
        npm run prisma:generate
        npm run tsx:prod
    stdin_open: true
    tty: true

networks:
  nishikata-coast-story:
    name: nishikata-coast-story
  reverse-proxy:
    name: reverse-proxy
    external: true
