services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    init: true
    networks:
      - nishikata-coast-story
    ports:
      - 11434:11434
    volumes:
      - ./volume/ollama/root/.ollama:/root/.ollama
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
    environment:
      - TZ=Asia/Tokyo
    stdin_open: true
    tty: true

networks:
  nishikata-coast-story:
    name: nishikata-coast-story
