name: Local LLM
version: 1.0.0
schema: v1
models:
  - name: qwen2.5-coder
    provider: ollama
    model: qwen2.5-coder
    roles:
      - chat
      # - autocomplete
      - embed
      - rerank
      - edit
      - apply
      - summarize
context:
  - provider: file
  - provider: code
  - provider: diff
  - provider: currentFile
  - provider: terminal
  - provider: open
  - provider: clipboard
  - provider: tree
  - provider: problems
  - provider: debugger
  - provider: repo-map
  - provider: os
rules:
  - name: Language Rule
    rule: Always speak Japanese
