services:
  mariadb:
    image: mariadb:12.0.2
    container_name: ncs-mariadb
    networks:
      - nishikata-coast-story
    ports:
      - 53306:3306
    volumes:
      - ./volume/mariadb/dev/var/lib/mysql:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}

networks:
  nishikata-coast-story:
    name: nishikata-coast-story
    external: true
