services:
  postgres:
    image: postgres:17.6
    container_name: ncs-postgres
    networks:
      - nishikata-coast-story
    ports:
      - 5432:5432
    volumes:
      - ./volume/postgres/dev/var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}

networks:
  nishikata-coast-story:
    name: nishikata-coast-story
    external: true
