name: QA Batch
on:
  pull_request:
    branches:
      - dev
jobs:
  qa-batch:
    name: QA Batch
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v6
      - name: Install Dependencies
        working-directory: backend/batch
        run: npm install
      - name: Run QA
        working-directory: backend/batch
        env:
          DOTENV_PRIVATE_KEY_ENV: ${{ secrets.DOTENV_PRIVATE_KEY_ENV }}
        run: npm run ncs:qa:github
      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: backend/batch
