name: Scan Leak
on:
  push:
    branches:
      - work
jobs:
  scan-leak:
    name: Scan Leak
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Install dotenvx
        run: curl -sfS https://dotenvx.sh | sh
      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_NOTIFY_USER_LIST: "@zen96k"
      - name: Run Dotenvx Scan
        run: dotenvx ext scan
