name: Setup Environment
on:
  push:
    branches:
      - work
    # paths:
    #   - "backend/batch/**"
jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node.jobs
        uses: actions/setup-node@v6
